<?xml version="1.0" encoding="UTF-8"?>

 
 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns="urn:skl:tp:vagvalsinfo:v2" 
    xmlns:tns="urn:skl:tp:vagvalsinfo:v2" 
    targetNamespace="urn:skl:tp:vagvalsinfo:v2" 
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified" 
    version="2.0">
	
	<xs:annotation>
		<xs:documentation>
		Tjänsteplattform
		Tjänste-schema för SökVagvalsinfo
    </xs:documentation>
	</xs:annotation>
	
	<xs:include schemaLocation="vagvalsinfo-anropsbehorighetsinfo-2.0.xsd"/>
    <xs:include schemaLocation="vagvalsinfo-virtualiseringsinfo-2.0.xsd"/>
    <xs:include schemaLocation="vagvalsinfo-tjanstekontraktinfo-2.0.xsd"/>
    <xs:include schemaLocation="vagvalsinfo-tjanstekomponentinfo-2.0.xsd"/>

	<xs:annotation>
		<xs:documentation>
		Meddelanden för operationer i SokVagvalsInfoInterface
    </xs:documentation>
	</xs:annotation>

    <xs:annotation>
        <xs:documentation>
            Operation hamtaAllaAnropsBehorigheter
        </xs:documentation>
    </xs:annotation>
    <xs:element name="hamtaAllaTjanstekontrakt" nillable="true"/>
    <xs:element name="hamtaAllaTjanstekontraktRequest" nillable="true" type="xs:NCName"/>
    <xs:element name="hamtaAllaTjanstekontraktResponse" type="tns:hamtaAllaTjanstekontraktResponseType"/>
    <xs:complexType name="hamtaAllaTjanstekontraktResponseType">
        <xs:sequence>
            <xs:element ref="tns:tjanstekontraktInfo" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:annotation>
        <xs:documentation>
            Operation hamtaAllaAnropsBehorigheter
        </xs:documentation>
    </xs:annotation>
    <xs:element name="hamtaAllaAnropsBehorigheter" nillable="true"/>
    <xs:element name="hamtaAllaAnropsBehorigheterRequest" nillable="true" type="xs:NCName"/>
    <xs:element name="hamtaAllaAnropsBehorigheterResponse" type="tns:hamtaAllaAnropsBehorigheterResponseType"/>
    <xs:complexType name="hamtaAllaAnropsBehorigheterResponseType">
        <xs:sequence>
            <xs:element ref="tns:anropsBehorighetsInfo" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:annotation>
		<xs:documentation>
		Operation hamtaAllaVirtualiseringar
    </xs:documentation>
	</xs:annotation>
	<xs:element name="hamtaAllaVirtualiseringar" nillable="true"/>
	<xs:element name="hamtaAllaVirtualiseringarRequest" nillable="true" type="xs:NCName"/>
	<xs:element name="hamtaAllaVirtualiseringarResponse" type="tns:hamtaAllaVirtualiseringarResponseType"/>
	<xs:complexType name="hamtaAllaVirtualiseringarResponseType">
		<xs:sequence>
			<xs:element ref="tns:virtualiseringsInfo" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

    <xs:annotation>
        <xs:documentation>
        Operation hamtaAllaTjanstekomponenter
    </xs:documentation>
    </xs:annotation>
    <xs:element name="hamtaAllaTjanstekomponenter" nillable="true"/>
    <xs:element name="hamtaAllaTjanstekomponenterRequest" nillable="true" type="xs:NCName"/>
    <xs:element name="hamtaAllaTjanstekomponenterResponse" type="tns:hamtaAllaTjanstekomponenterResponseType"/>
    <xs:complexType name="hamtaAllaTjanstekomponenterResponseType">
        <xs:sequence>
            <xs:element ref="tns:tjanstekomponentInfo" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
