<?xml version="1.0" encoding="UTF-8"?>


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns="urn:skl:tp:vagvalsinfo:v2"
    targetNamespace="urn:skl:tp:vagvalsinfo:v2"
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified">

	<xs:import schemaLocation="../../core_components/vagvalsinfo-coretypes-1.0.xsd" namespace="urn:skl:tp:core:v1"/>
	<xs:element name="tjanstekontraktInfo" type="tjanstekontraktInfoType"/>
	<xs:complexType name="tjanstekontraktInfoType">
		<xs:sequence>
            <xs:element name="namnrymd"    type="xs:string"/>
            <xs:element name="majorVersion"     type="xs:string"/>
            <xs:element name="minorVersion"     type="xs:string"/>
            <xs:element name="beskrivning" type="xs:string"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
