<?xml version="1.0" encoding="UTF-8"?>


<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="urn:skl:tp:vagvalsinfo:v2" targetNamespace="urn:skl:tp:vagvalsinfo:v2">
	<wsdl:import namespace="urn:skl:tp:vagvalsinfo:v2" location="vagvalsinfo-sokvagvalsinfo-2.0.wsdl"/>
	<wsdl:service name="SokVagvalsServiceSoap11LitDocService">
		<wsdl:port name="SokVagvalsSoap11LitDocPort" binding="tns:SokVagvalsInfoInterfaceSoap11DocLitBinding">
			<soap:address location="http://tempuri.org/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>