version: '3'
services:
  tak-web:
    build: ./tak-web
    ports:
      - "8001:8080"
    environment:
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.datasource.url: jdbc:mysql://tak-mysql:3306/tp_admin?autoReconnect=true
      spring.datasource.username: tpadminuser
      spring.datasource.password: tpadminpassword
  tak-services:
    build: ./tak-services
    ports:
      - "8002:8080"
    environment:
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.datasource.url: jdbc:mysql://tak-mysql:3306/tp_admin?autoReconnect=true
      spring.datasource.username: tpadminuser
      spring.datasource.password: tpadminpassword
  tak-mysql:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: tp_admin
      MYSQL_USER: tpadminuser
      MYSQL_PASSWORD: tpadminpassword
    ports:
      - "3306:3306"
    volumes:
      - ./resources/sql/tp-admin-DDL.sql:/docker-entrypoint-initdb.d/tp-admin-DDL.sql