version: '3'
services:
  tak-web:
    build: ./tak-web
    depends_on:
      tak-mysql:
        condition: service_healthy
    ports:
      - "8001:8080"
    volumes:
      - ./resources/etc/log4j2-console.xml:/etc/tak/log4j2-console.xml
    environment:
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.datasource.url: jdbc:mysql://tak-mysql:3306/tp_admin?autoReconnect=true
      spring.datasource.username: tpadminuser
      spring.datasource.password: tpadminpassword
      spring.sql.init.platform: mysql
      logging.config: /etc/tak/log4j2-console.xml
      spring.session.jdbc.schema: "classpath:org/springframework/session/jdbc/schema-mysql.sql"
      spring.session.store-type: jdbc
      server.servlet.session.timeout: 30m
      spring.session.jdbc.initialize-schema: always
  tak-services:
    build: ./tak-services
    depends_on:
      tak-mysql:
        condition: service_healthy
    ports:
      - "8002:8080"
    volumes:
      - ./resources/etc/log4j2-console.xml:/etc/tak/log4j2-console.xml
    environment:
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.datasource.url: jdbc:mysql://tak-mysql:3306/tp_admin?autoReconnect=true
      spring.datasource.username: tpadminuser
      spring.datasource.password: tpadminpassword
  tak-monitor:
    build: ./tak-monitor
    depends_on:
      - tak-services
    volumes:
      - ./resources/etc/log4j2-console.xml:/etc/tak/log4j2-console.xml
    environment:
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.datasource.url: jdbc:mysql://tak-mysql:3306/tp_admin?autoReconnect=true
      spring.datasource.username: tpadminuser
      spring.datasource.password: tpadminpassword
      logging.config: /etc/tak/log4j2-console.xml
      tak.monitor.reset.nodes.0.url: http://tak-services:8080/tak-services/reset/pv

  tak-mysql:
    image: mysql:8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: tp_admin
      MYSQL_USER: tpadminuser
      MYSQL_PASSWORD: tpadminpassword
    ports:
      - "3306:3306"
    volumes:
      - ./resources/sql/tp-admin-testdb.sql:/docker-entrypoint-initdb.d/tp-admin-DDL.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      tak-mysql:
        condition: service_healthy
    ports:
      - 8081:80
    environment:
      PMA_HOST: tak-mysql
      PMA_USER: tpadminuser
      PMA_PASSWORD: tpadminpassword
