services:
  postgres:
    image: postgres:16-alpine
    container_name: keycloak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    container_name: keycloak
    restart: unless-stopped
    #volumes:
    #  - ./master-realm.json:/opt/keycloak/data/import/master-realm.json
    command: start-dev #--import-realm
    environment:
      # Databas
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Utvecklingsmiljö
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_LOG_LEVEL: INFO
    ports:
      - "8080:8080"   # HTTP
      - "9000:9000"   # Management / Health endpoint
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default

volumes:
  postgres_data:
    driver: local
