---
# Source: tak/templates/tak-web-ingressroutes.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: tak
  name: tak-http
  namespace: dtjp
spec:
  routes:
    - kind: Rule
      match: Host(`bks-lab.admin.ntjp.se`) && PathPrefix(`/tak-web`)
      middlewares:
        - name: ipwhitelist
        - name: redirect-https
      services:
        - kind: Service
          name: tak-web-svc
          port: 8080
    - kind: Rule
      match: Host(`bks-lab.admin.ntjp.se`) && PathPrefix(`/tak-services/reset/pv`)
      middlewares:
        - name: ipwhitelist
        - name: redirect-https
      services:
        - kind: Service
          name: tak-services-svc
          port: 8080
---
# Source: tak/templates/tak-web-ingressroutes.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: tak
  name: tak-https
  namespace: dtjp
spec:
  routes:
    - kind: Rule
      match: Host(`bks-lab.admin.ntjp.se`) && PathPrefix(`/tak-web`)
      middlewares:
        - name: ipwhitelist
      priority: 10
      services:
        - kind: Service
          name: tak-web-svc
          passHostHeader: true
          port: 8080
          responseForwarding:
            flushInterval: 1ms
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              sameSite: none
              secure: true
          strategy: RoundRobin
          weight: 10
    - kind: Rule
      match: Host(`bks-lab.admin.ntjp.se`) && PathPrefix(`/tak-services/reset/pv`)
      middlewares:
        - name: ipwhitelist
      priority: 10
      services:
        - kind: Service
          name: tak-services-svc
          passHostHeader: true
          port: 8080
          responseForwarding:
            flushInterval: 1ms
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              sameSite: none
              secure: true
          strategy: RoundRobin
          weight: 10
  tls:
    domains:
      - main: bks-lab.admin.ntjp.se
    secretName: bks-lab.admin.ntjp.se-letsencrypt
---
# Source: tak/templates/tak-web-ingressroutes.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
