apiVersion: v1
kind: ConfigMap
metadata:
    name: tak-config-files
data:
    log4j2.xml: |
        <Configuration status="WARN" monitorInterval="30">
        <Properties>
          <Property name="LOG_PATTERN">
          %d %-5p [%t] %-30c - %X{corr.id} %m%n
          </Property>
        </Properties>

        <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout pattern="${LOG_PATTERN}"/>
        </Console>
        </Appenders>

        <Loggers>
          <Logger name="se.skltp.tak" level="INFO"/>
          <Logger name="org.springframework.web" level="WARN"/>
          <Logger name="org.hibernate" level="WARN"/>
          <Logger name="org.apache.cxf" level="WARN"/>
          <AsyncRoot level="INFO">
            <AppenderRef ref="Console"/>
          </AsyncRoot>
        </Loggers>
        </Configuration>
    log4j2-debug.xml: |
        <Configuration status="WARN" monitorInterval="30">
        <Properties>
          <Property name="LOG_PATTERN">
          %d %-5p [%t] %-30c - %X{corr.id} %m%n
          </Property>
        </Properties>

        <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout pattern="${LOG_PATTERN}"/>
        </Console>
        </Appenders>

        <Loggers>
          <Logger name="se.skltp.tak" level="DEBUG"/>
          <Logger name="org.springframework.web" level="INFO"/>
          <Logger name="org.hibernate" level="WARN"/>
          <Logger name="org.apache.cxf" level="WARN"/>
          <AsyncRoot level="INFO">
            <AppenderRef ref="Console"/>
          </AsyncRoot>
        </Loggers>
        </Configuration>
