apiVersion: v1
kind: ConfigMap
metadata:
    name: tak-config-files
data:
    log4j2.xml: |
        <Configuration status="WARN" monitorInterval="30">

        <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <JsonTemplateLayout eventTemplateUri="file:{{.Values.logConfig.jsonEventTemplate.path}}"/>
        </Console>
        </Appenders>

        <Loggers>
        {{- range .Values.logConfig.loggers }}
          <Logger name="{{ .name }}" level="{{ .level }}"/>
        {{- end }}
          <Root level="{{ .Values.logConfig.root.level }}">
            <AppenderRef ref="Console"/>
          </Root>
        </Loggers>
        </Configuration>

    tak-ecs-template.json: |
        {
            "@timestamp": {
                "$resolver": "timestamp",
                "pattern": {
                    "format": "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
                    "timeZone": "UTC"
                }
            },
            "ecs.version": "1.2.0",
            "log.level": {
                "$resolver": "level",
                "field": "name"
            },
            "message": {
                "$resolver": "message",
                "stringified": true
            },
            "process.thread.name": {
                "$resolver": "thread",
                "field": "name"
            },
            "log.logger": {
                "$resolver": "logger",
                "field": "name"
            },
            "labels": {
                "$resolver": "mdc",
                "flatten": true,
                "stringified": true
            },
            "tags": {
                "$resolver": "ndc"
            },
            "error.type": {
                "$resolver": "exception",
                "field": "className"
            },
            "error.message": {
                "$resolver": "exception",
                "field": "message"
            },
            "error.stack_trace": {
                "$resolver": "exception",
                "field": "stackTrace",
                "stackTrace": {
                    "stringified": true
                }
            }
        }