apiVersion: apps/v1
kind: Deployment
metadata:
  name: tak-web
spec:
  replicas: {{ .Values.deployments.takweb.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: tak-web
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: tak-web
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.git/commit-hash: {{ .Values.git.commit.hash }}
        app: tak-web
        elasticGrokFilter: {{ .Values.deployments.takweb.elasticGrokFilter }}
        monitoring: prometheus
    spec:
      imagePullSecrets:
        - name: regcred

      volumes:
        - name: {{ .Values.tls.bundle.name }}-keystore
          secret:
            secretName: {{ .Values.tls.bundle.tlsSecret }}
        - name: {{ .Values.tls.bundle.name }}-truststore
          configMap:
            name: {{ .Values.tls.bundle.truststoreConfigMap }}
      containers:
        - name: tak-web
          image: "{{ .Values.repository }}tak-web:{{ .Values.container.takweb.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.takweb.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Values.tls.bundle.name }}-keystore
              mountPath: /etc/certs/{{ .Values.tls.bundle.name }}-keystore
            - name: {{ .Values.tls.bundle.name }}-truststore
              mountPath: /etc/certs/{{ .Values.tls.bundle.name }}-truststore
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: actuators
              containerPort: 8089
              protocol: TCP
          # Injection of startup, liveness, and/or readiness probes below.
          {{- .Values.probes_web | toYaml | nindent 10 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000 # ind-app
            seccompProfile:
              type: RuntimeDefault
          resources: # Block-templated memory and CPU resources.
            {{- toYaml .Values.deployments.takweb.resources | nindent 12 }}
          {{- with .Values.deployments.takweb.environment.variables }}
          {{- if .map }}
          env:
            {{- range $k, $v := .map }}
            - name: {{ $k }}
              value: {{ $v }}
            {{- end }}
          {{- end }}
          {{- end }}
          envFrom:
            {{- range .Values.deployments.takweb.environment.variables._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.deployments.takweb.environment.variables.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.deployments.takweb.environment.variables.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
