apiVersion: apps/v1
kind: Deployment
metadata:
  name: tak-monitor
spec:
  replicas: {{ .Values.deployments.takmonitor.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tak-monitor
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: tak-monitor
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app: tak-monitor
        elasticGrokFilter: {{ .Values.deployments.takmonitor.elasticGrokFilter }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: tak-monitor
          image: "{{ .Values.repository }}tak-monitor:{{ .Values.container.takmonitor.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /tak-monitor/actuator/health/liveness
              port: http
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            failureThreshold: 12
            httpGet:
              path: /tak-monitor/actuator/health/readiness
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000 # ind-app
            seccompProfile:
              type: RuntimeDefault
          resources: # Block-templated memory and CPU resources.
            {{- toYaml .Values.deployments.takmonitor.resources | nindent 12 }}
          {{- with .Values.deployments.takmonitor.environment.variables }}
          {{- if .map }}
          env:
            {{- range $k, $v := .map }}
            - name: {{ $k }}
              value: {{ $v }}
            {{- end }}
          {{- end }}
          {{- end }}
          envFrom:
            {{- range .Values.deployments.takmonitor.environment.variables._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.deployments.takmonitor.environment.variables.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.deployments.takmonitor.environment.variables.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
      serviceAccount: serviceaccount-tak-monitor