apiVersion: apps/v1
kind: Deployment
metadata:
  name: tak-services
spec:
  replicas: {{ .Values.deployments.takservices.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tak-services
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: tak-services
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app: tak-services
        elasticGrokFilter: {{ .Values.deployments.takservices.elasticGrokFilter }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: tak-services
          image: "{{ .Values.repository }}tak-services:{{ .Values.container.takservices.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.takservices.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # Injection of startup, liveness, and/or readiness probes below.
          {{- .Values.probes_services | toYaml | nindent 10 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000 # ind-app
            seccompProfile:
              type: RuntimeDefault
          resources: # Block-templated memory and CPU resources.
            {{- toYaml .Values.deployments.takservices.resources | nindent 12 }}
          {{- with .Values.deployments.takservices.environment.variables }}
          {{- if .map }}
          env:
            {{- range $k, $v := .map }}
            - name: {{ $k }}
              value: {{ $v }}
            {{- end }}
          {{- end }}
          {{- end }}
          envFrom:
            {{- range .Values.deployments.takservices.environment.variables._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.deployments.takservices.environment.variables.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.deployments.takservices.environment.variables.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}