apiVersion: apps/v1
kind: Deployment
metadata:
  name: tak-services
spec:
  replicas: {{ .Values.deployments.takservices.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: tak-services
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: tak-services
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app: tak-services
        elasticGrokFilter: {{ .Values.deployments.takservices.elasticGrokFilter }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: tak-services
          image: "{{ .Values.repository }}tak-services:{{ .Values.container.takservices.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            failureThreshold: 10
            httpGet:
              path: /tak-services/appinfo/status/liveness
              port: http
          readinessProbe:
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            failureThreshold: 10
            httpGet:
              path: /tak-services/appinfo/status/readiness
              port: http
          resources:
            limits:
              memory: {{ .Values.deployments.takservices.memory }}
            requests:
              cpu: 200m
              memory: {{ .Values.deployments.takservices.memory }}
          {{- with .Values.deployments.takservices.environment.variables }}
          {{- if .map }}
          env:
            {{- range $k, $v := .map }}
            - name: {{ $k }}
              value: {{ $v }}
            {{- end }}
          {{- end }}
          {{- end }}
          envFrom:
            {{- range .Values.deployments.takservices.environment.variables._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.deployments.takservices.environment.variables.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.deployments.takservices.environment.variables.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}