apiVersion: apps/v1
kind: Deployment
metadata:
  name: tak-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tak-web
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: tak-web
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app: tak-web
    spec:
      imagePullSecrets:
        - name: regcred
      {{ if .Values.initContainer }}
      volumes:
        - name: consumer-pem-vol
          secret:
            secretName: {{ .Values.pem_to_pfx.consumer.secretName }}
        - name: pkcs12-volume
      initContainers:
        - name: {{ .Values.initContainer.certGen.image.name }}
          image: "{{ .Values.repository }}{{ .Values.initContainer.certGen.image.name }}:{{ .Values.initContainer.certGen.image.tag }}"
          imagePullPolicy: {{ .Values.initContainer.certGen.image.pullPolicy | default "Always" }}
          volumeMounts:
            - name: pkcs12-volume
              mountPath: /opt/certs/pkcs12
              {{- with .Values.pem_to_pfx }}
            - name: consumer-pem-vol
              mountPath: {{ .pem.path }}/{{ .consumer.pemKeyFile }}
              subPath: tls.key
            - name: consumer-pem-vol
              mountPath: {{ .pem.path }}/{{ .consumer.pemCertFile }}
              subPath: tls.crt
              {{- end }}
          env:
            {{- with .Values.pem_to_pfx }}
            - name:  PEM2PFX_CONSUMER_PEM_PATH
              value: {{ .pem.path }}/{{ .consumer.pemCertFile }}
            - name: PEM2PFX_CONSUMER_KEY_PATH
              value: {{ .pem.path }}/{{ .consumer.pemKeyFile }}
            - name: PEM2PFX_CONSUMER_PFX_PATH
              value: {{ .pfx.path }}/{{ .consumer.pfxFile }}
            - name: PEM2PFX_CONSUMER_PFX_PASSWORD
              value: {{ .consumer.password }}
            {{- end }}
      {{- end }}
      containers:
        - name: tak-web
          image: "{{ .Values.repository }}tak-web:{{ .Values.container.takweb.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            failureThreshold: 10
            httpGet:
              path: /tak-web/actuator/health/liveness
              port: http
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            failureThreshold: 10
            httpGet:
              path: /tak-web/actuator/health/readiness
              port: http
          resources:
            limits:
              cpu: 800m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 1Gi
          envFrom:
            {{- range .Values.deployments.takweb.environment.variables._default_config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.deployments.takweb.environment.variables.config_maps }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.deployments.takweb.environment.variables.secrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
