apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-http
spec:
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingressroute.hostUrl }}`) && PathPrefix(`/tak-web`)
      middlewares:
        - name: ipwhitelist
        - name: redirect-https
      services:
        - kind: Service
          name: tak-web-svc
          port: 8080
    - kind: Rule
      match: Host(`{{ .Values.ingressroute.hostUrl }}`) && PathPrefix(`/tak-services/reset/pv`)
      middlewares:
        - name: ipwhitelist
        - name: redirect-https
      services:
        - kind: Service
          name: tak-services-svc
          port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-https
spec:
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingressroute.hostUrl }}`) && PathPrefix(`/tak-web`)
      middlewares:
        - name: ipwhitelist
      priority: 10
      services:
        - kind: Service
          name: tak-web-svc
          passHostHeader: true
          port: 8080
          responseForwarding:
            flushInterval: 1ms
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              sameSite: none
              secure: true
          strategy: RoundRobin
          weight: 10
    - kind: Rule
      match: Host(`{{ .Values.ingressroute.hostUrl }}`) && PathPrefix(`/tak-services/reset/pv`)
      middlewares:
        - name: ipwhitelist
      priority: 10
      services:
        - kind: Service
          name: tak-services-svc
          passHostHeader: true
          port: 8080
          responseForwarding:
            flushInterval: 1ms
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              sameSite: none
              secure: true
          strategy: RoundRobin
          weight: 10
  tls:
    domains:
      - main: tak.dev.ntjp.se
    secretName: tak.dev.ntjp.se-letsencrypt