apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localhost-cert
spec:
  secretName: localhost-letsencrypt
  issuerRef:
    name: letsencrypt-dev
    kind: Issuer
  dnsNames:
    - localhost