apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tak-web-pod-monitor
  labels:
    app: tak-web
spec:
  selector:
    matchLabels:
      monitoring: prometheus
  podMetricsEndpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s