apiVersion: v1
kind: Service
metadata:
  name: tak-web-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tak-web
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http