{{- range $.Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: {{ .type }}
  selector: {{- include "tak.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: http
---
{{- end }}