apiVersion: v1
kind: ConfigMap
metadata:
  name: tak-web-configmap
data:
  tak.web.resource.dir: /etc/tak

  # Order handling (default off)
  {{ if .Values.tls.bundle.active }}
  tak.bestallning.on: "true"
  tak.bestallning.url.0.name: FRIENDLY
  tak.bestallning.url.0.url: https://BS.URL/bs-api/api/takOrders

  spring.ssl.bundle.pem.{{ .Values.tls.bundle.name }}.keystore.certificate: /etc/certs/{{ .Values.tls.bundle.name }}-keystore/tls.crt
  spring.ssl.bundle.pem.{{ .Values.tls.bundle.name }}.keystore.privatekey: /etc/certs/{{ .Values.tls.bundle.name }}-keystore/tls.key
  spring.ssl.bundle.pem.{{ .Values.tls.bundle.name }}.truststore.certificate: /etc/certs/{{ .Values.tls.bundle.name }}-truststore/ca.crt
  {{- end }}