apiVersion: v1
kind: ConfigMap
metadata:
  name: tak-web-configmap-default
data:
  TAK_WEB_RESOURCE_DIR: "{{ .Values.takWeb.resourceDir }}"

  # Order handling (default off)
  {{- if .Values.tls.bundle.active }}
  TAK_BESTALLNING_ON: "{{ .Values.takWeb.bestallning.on }}"
  TAK_BESTALLNING_URL_0_NAME: "{{ .Values.takWeb.bestallning.url0Name }}"
  TAK_BESTALLNING_URL_0_URL: "{{ .Values.takWeb.bestallning.url0Url }}"

  SPRING_SSL_BUNDLE_PEM_{{ .Values.tls.bundle.name | upper }}_KEYSTORE_CERTIFICATE: "{{ .Values.paths.certs }}/{{ .Values.tls.bundle.name }}-keystore/tls.crt"
  SPRING_SSL_BUNDLE_PEM_{{ .Values.tls.bundle.name | upper }}_KEYSTORE_PRIVATEKEY: "{{ .Values.paths.certs }}/{{ .Values.tls.bundle.name }}-keystore/tls.key"
  SPRING_SSL_BUNDLE_PEM_{{ .Values.tls.bundle.name | upper }}_TRUSTSTORE_CERTIFICATE: "{{ .Values.paths.certs }}/{{ .Values.tls.bundle.name }}-truststore/ca.crt"
  {{- end }}