apiVersion: v1
kind: ConfigMap
metadata:
  name: tak-web-configmap-default
data:
  # Set the logging level for the root of the namespace.
  # This becomes the default logging level for all Loggers.
  .level: WARNING

  # List all the log handlers
  handlers: java.util.logging.FileHandler

  # Everything is logged to the file writer
  java.util.logging.FileHandler.level: ALL
  java.util.logging.FileHandler.pattern: /var/log/tomcat/axel/axel.log
  java.util.logging.FileHandler.append: "true"
  java.util.logging.FileHandler.formatter: java.util.logging.SimpleFormatter

  # SHS Broker certificate
  shsRsKeyStoreParameters.resource: /etc/axel/certs/268B5EC441D822B2.p12
  shsRsKeyStoreParameters.type: pkcs12
  shsRsTrustStoreParameters.resource: /etc/axel/certs/steria-ca.jks
  shsRsTrustStoreParameters.type: jks

  # RIV-SHS certificate - relative path!
  keyStoreParameters.resource: certs/tp.jks
  keyStoreParameters.type: jks
  trustStoreParameters.resource: certs/truststore.jks
  trustStoreParameters.type: jks

  # Activemq properties
  activemq.brokerURL: "failover:(tcp://axel-amq:61616)?randomize=false&timeout=10000&jms.prefetchPolicy.queuePrefetch=5"
  activemq.maxConnections: "1"
  spring.activemq.packages.trusted: se.inera.axel.shs.broker.messagestore,se.inera.axel.shs.xml.label,java.util

  # SHS Broker properties
  nodeId: IneraTest-DEV
  orgId: "1234567890"
  shs.label.status: test

  shs.ldap.url: ldap://public.openshs.se:389/L=SHS
  shs.ldap.admin.url: ldap://update.openshs.se:389/L=SHS
  shs.ldap.admin.userDn: cn=ineraadmin,ou=katalogadmin

  # RIV-SHS properties
  productServiceRestEndpoint: http://localhost:8090/shs-broker/services/products
  rsEndpoint: http://localhost:8090/shs-broker/rs

  # for inloggning
  tak.db.url: "jdbc:mysql://ind-dtjp-rh8-mysql.ind1.sth.basefarm.net:3306/takv3?autoReconnect=true"