apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-http
spec:
  routes:
    {{- range .Values.ingressRoutes.http.routes }}
    - kind: {{ .kind }}
      match: Host(`{{ .match_host }}`) && PathPrefix(`{{ .pathPrefix }}`)
      middlewares: {{-  toYaml .middlewares | nindent 8}}
      services:
        - kind: Service
          name: {{.service.name }}
          port: {{.service.port }}
    {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-https
spec:
  routes:
    {{- range .Values.ingressRoutes.https.routes }}
    - kind: {{ .kind }}
      match: Host(`{{ .match_host }}`) && PathPrefix(`{{ .pathPrefix }}`)
      middlewares: {{-  toYaml .middlewares | nindent 8}}
      priority: 10
      services:
        - kind: Service
          name: {{ .service.name }}
          passHostHeader: true
          port: {{ .service.port }}
          responseForwarding:
            flushInterval: {{ .service.responseForwarding.flushInterval }}
          scheme: http
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              sameSite: none
              secure: true
          strategy: {{ .service.responseForwarding.strategy }}
          weight: {{ .service.responseForwarding.weight }}
    {{- end }}
  tls:
    domains:
      - main: {{ .Values.ingressRoutes.tls.host.main }}
    secretName: {{ .Values.ingressRoutes.tls.secretName }}