apiVersion: v1
kind: ConfigMap
metadata:
  name: tak-monitor-configmap-default
data:
  # TAK Cache reset settings
  TAK_MONITOR_RESET_USE_POD_LOOKUP: "{{ .Values.takMonitor.reset.usePodLookup }}"
  TAK_MONITOR_RESET_POD_NAMESPACE: "{{ tpl .Values.takMonitor.reset.podNamespace . }}"

{{- range $index, $node := .Values.takMonitor.reset.nodes }}
  TAK_MONITOR_RESET_NODES_{{ $index }}_LABEL: "{{ $node.label }}"
  TAK_MONITOR_RESET_NODES_{{ $index }}_URL: "{{ $node.url }}"
{{- end }}
