apiVersion: v1
kind: ConfigMap
metadata:
  name: tak-configmap-default
data:
  # Database settings
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "{{ .Values.spring.datasource.driverClassName }}"
  SPRING_DATASOURCE_URL: "{{ .Values.spring.datasource.url }}"

  # Logging
  SPRING_PROFILES_ACTIVE: "{{ .Values.spring.profiles.active }}"

  MANAGEMENT_SERVER_PORT: "{{ .Values.management.serverPort }}"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '{{ .Values.management.endpointsWebExposureInclude | join "," }}'
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "{{ .Values.management.endpointPrometheusEnabled }}"

  SERVER_TOMCAT_ACCESSLOG_BUFFERED: "{{ .Values.server.tomcat.accesslog.buffered }}"
  SERVER_TOMCAT_ACCESSLOG_DIRECTORY: "{{ .Values.server.tomcat.accesslog.directory }}"
  SERVER_TOMCAT_ACCESSLOG_ENABLED: "{{ .Values.server.tomcat.accesslog.enabled }}"
  SERVER_TOMCAT_ACCESSLOG_FILE_DATE_FORMAT: "{{ .Values.server.tomcat.accesslog.fileDateFormat }}"
  SERVER_TOMCAT_ACCESSLOG_PREFIX: "{{ .Values.server.tomcat.accesslog.prefix }}"
  SERVER_TOMCAT_ACCESSLOG_SUFFIX: "{{ .Values.server.tomcat.accesslog.suffix }}"
  SERVER_TOMCAT_ACCESSLOG_PATTERN: >-
    {{ .Values.server.tomcat.accesslog.pattern }}
