package se.skltp.tak.vagval.wsdl.v2;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-23T14:49:58.134+02:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "urn:skl:tp:vagval:v2", name = "VisaVagvalsInterface")
@XmlSeeAlso({se.skltp.tak.vagvalsinfo.wsdl.v2.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VisaVagvalsInterface {

    @WebMethod
    @WebResult(name = "visaVagvalResponse", targetNamespace = "urn:skl:tp:vagval:v2", partName = "response")
    public VisaVagvalResponse visaVagval(

        @WebParam(partName = "parameters", name = "visaVagvalRequest", targetNamespace = "urn:skl:tp:vagval:v2")
        VisaVagvalRequest parameters
    );

    @WebMethod
    @WebResult(name = "resetVagvalCacheResponse", targetNamespace = "urn:skl:tp:vagval:v2", partName = "response")
    public ResetVagvalCacheResponse resetVagvalCache(

        @WebParam(partName = "parameters", name = "resetVagvalCacheRequest", targetNamespace = "urn:skl:tp:vagval:v2")
        ResetVagvalCacheRequest parameters
    );
}
