create table AnropsAdress
(
    id                  bigint generated by default as identity,
    deleted             boolean,
    pubVersion          varchar(255),
    updatedBy           varchar(255),
    updatedTime         timestamp(6),
    adress              varchar(255),
    version             bigint not null,
    rivTaProfil_id      bigint not null,
    tjanstekomponent_id bigint not null,
    primary key (id)
);
create table Anropsbehorighet
(
    id                  bigint generated by default as identity,
    deleted             boolean,
    pubVersion          varchar(255),
    updatedBy           varchar(255),
    updatedTime         timestamp(6),
    fromTidpunkt        date,
    integrationsavtal   varchar(255),
    tomTidpunkt         date,
    version             bigint not null,
    logiskAdress_id     bigint not null,
    tjanstekonsument_id bigint not null,
    tjanstekontrakt_id  bigint not null,
    primary key (id)
);
create table Anvandare
(
    id            bigint generated by default as identity,
    administrator boolean,
    anvandarnamn  varchar(255) not null unique,
    losenord_hash varchar(255),
    version       bigint       not null,
    primary key (id)
);
create table Filter
(
    id                  bigint generated by default as identity,
    deleted             boolean,
    pubVersion          varchar(255),
    updatedBy           varchar(255),
    updatedTime         timestamp(6),
    servicedomain       varchar(255),
    version             bigint not null,
    anropsbehorighet_id bigint not null,
    primary key (id)
);
create table Filtercategorization
(
    id          bigint generated by default as identity,
    deleted     boolean,
    pubVersion  varchar(255),
    updatedBy   varchar(255),
    updatedTime timestamp(6),
    category    varchar(255),
    version     bigint not null,
    filter_id   bigint not null,
    primary key (id)
);
create table Locktb
(
    tabell varchar(255) not null,
    locked integer,
    primary key (tabell)
);
create table LogiskAdress
(
    id          bigint generated by default as identity,
    deleted     boolean,
    pubVersion  varchar(255),
    updatedBy   varchar(255),
    updatedTime timestamp(6),
    beskrivning varchar(255),
    hsaId       varchar(255),
    version     bigint not null,
    primary key (id)
);
create table PubVersion
(
    id            bigint generated by default as identity,
    data          oid,
    formatVersion bigint not null,
    kommentar     varchar(255),
    storlek       bigint not null,
    time          timestamp(6),
    utforare      varchar(255),
    version       bigint not null,
    primary key (id)
);
create table RivTaProfil
(
    id          bigint generated by default as identity,
    deleted     boolean,
    pubVersion  varchar(255),
    updatedBy   varchar(255),
    updatedTime timestamp(6),
    beskrivning varchar(255),
    namn        varchar(255),
    version     bigint not null,
    primary key (id)
);
create table TAKSettings
(
    id           bigint generated by default as identity,
    settingName  varchar(255) not null unique,
    settingValue oid          not null,
    version      bigint       not null,
    primary key (id)
);
create table Tjanstekomponent
(
    id          bigint generated by default as identity,
    deleted     boolean,
    pubVersion  varchar(255),
    updatedBy   varchar(255),
    updatedTime timestamp(6),
    beskrivning varchar(255),
    hsaId       varchar(255),
    version     bigint not null,
    primary key (id)
);
create table Tjanstekontrakt
(
    id           bigint generated by default as identity,
    deleted      boolean,
    pubVersion   varchar(255),
    updatedBy    varchar(255),
    updatedTime  timestamp(6),
    beskrivning  varchar(255),
    majorVersion bigint not null,
    minorVersion bigint not null,
    namnrymd     varchar(255),
    version      bigint not null,
    primary key (id)
);
create table Vagval
(
    id                 bigint generated by default as identity,
    deleted            boolean,
    pubVersion         varchar(255),
    updatedBy          varchar(255),
    updatedTime        timestamp(6),
    fromTidpunkt       date,
    tomTidpunkt        date,
    version            bigint not null,
    anropsAdress_id    bigint not null,
    logiskAdress_id    bigint not null,
    tjanstekontrakt_id bigint not null,
    primary key (id)
);
alter table if exists AnropsAdress add constraint FKkjoc0te5hv32trad7rnyj95h6 foreign key (rivTaProfil_id) references RivTaProfil;
alter table if exists AnropsAdress add constraint FKgv6borcp70omgihq48fthhamh foreign key (tjanstekomponent_id) references Tjanstekomponent;
alter table if exists Anropsbehorighet add constraint FKprhjvdww7w9yuql7x6804vmc2 foreign key (logiskAdress_id) references LogiskAdress;
alter table if exists Anropsbehorighet add constraint FKfi6xpovy5phvre06mer2f2h9q foreign key (tjanstekonsument_id) references Tjanstekomponent;
alter table if exists Anropsbehorighet add constraint FKkaamxv2h20d3jiicwwrnofntr foreign key (tjanstekontrakt_id) references Tjanstekontrakt;
alter table if exists Filter add constraint FK6fymvlsugsijaf1b1chttjcfu foreign key (anropsbehorighet_id) references Anropsbehorighet;
alter table if exists Filtercategorization add constraint FKnd08lnxiycqs947ngofil2ent foreign key (filter_id) references Filter;
alter table if exists Vagval add constraint FK3jhxnd1a85x7n6eq70m5dot95 foreign key (anropsAdress_id) references AnropsAdress;
alter table if exists Vagval add constraint FKnv6ybpvlgdwyrleerywf4r8m6 foreign key (logiskAdress_id) references LogiskAdress;
alter table if exists Vagval add constraint FKb4ts74h8entt0r6o1hdmdaiis foreign key (tjanstekontrakt_id) references Tjanstekontrakt;
