<?xml version="1.0" encoding="UTF-8"?>

 
 <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:skl:tp:core:v1" targetNamespace="urn:skl:tp:core:v1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!--
							bastyper för simpleTypes att användas generellt inom komponenten. 
							Delar av dessa kan säker på sikt bytas mot ISO-typer.
	-->
	<xs:simpleType name="UUID">
		<xs:restriction base="xs:string">
<!--
							Behöver bytas mot en precis definition för ett UUID.
							Tills vidare finns typen för att indikera när ett element ska ha
							ett globalt unikt värde, snarare än ett specifikt format för detta värde.
-->
		</xs:restriction>
	</xs:simpleType>
</xs:schema>