package se.skltp.tak.vagvalsinfo.wsdl.v2;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-09-23T13:59:11.637+02:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "SokVagvalsServiceSoap11LitDocService",
                  targetNamespace = "urn:skl:tp:vagvalsinfo:v2")
public class SokVagvalsServiceSoap11LitDocService extends Service {

    public static final QName SERVICE = new QName("urn:skl:tp:vagvalsinfo:v2", "SokVagvalsServiceSoap11LitDocService");
    public static final QName SokVagvalsSoap11LitDocPort = new QName("urn:skl:tp:vagvalsinfo:v2", "SokVagvalsSoap11LitDocPort");

    public SokVagvalsServiceSoap11LitDocService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SokVagvalsServiceSoap11LitDocService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SokVagvalsServiceSoap11LitDocService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SokVagvalsServiceSoap11LitDocService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SokVagvalsInfoInterface
     */
    @WebEndpoint(name = "SokVagvalsSoap11LitDocPort")
    public SokVagvalsInfoInterface getSokVagvalsSoap11LitDocPort() {
        return super.getPort(SokVagvalsSoap11LitDocPort, SokVagvalsInfoInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SokVagvalsInfoInterface
     */
    @WebEndpoint(name = "SokVagvalsSoap11LitDocPort")
    public SokVagvalsInfoInterface getSokVagvalsSoap11LitDocPort(WebServiceFeature... features) {
        return super.getPort(SokVagvalsSoap11LitDocPort, SokVagvalsInfoInterface.class, features);
    }

}
