repository: docker.drift.inera.se/ntjp/

ingressroute:
  hostName: base.env.url # This should be overridden and set to your environment's base name.

exportCronJob:
  schedule: "30 17 * * *"

deployments:
  takweb:
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.

  takservices:
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.

  takmonitor:
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
        # Nothing yet. Override to supply your own values.
        secrets:
        # Nothing yet.

  takintegration:
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.

initContainer:
  certGen:
    image:
      name: cert-generator-utility
      tag: 4.4.0-RC1

pem_to_pfx:
  envPrefix: PEM2PFX
  pem:
    path: /opt/certs/pem
  pfx:
    path: /opt/certs/pkcs12
  consumer:
    secretName: test.esb.ntjp.sjunet.org
    pemCertFile: consumer.crt
    pemKeyFile: consumer.key
    pfxFile: consumer.pfx
    password: password
