repository: docker.drift.inera.se/ntjp/

ingressroute:
  bksHostName: base.env.url # This should be overridden and set to your environment's base name.

exportCronJob:
  schedule: "30 17 * * *"

deployments:
  takweb:
    replicaCount: 1
    elasticGrokFilter: tak-web
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.

  takservices:
    replicaCount: 1
    elasticGrokFilter: tak-services
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.

  takmonitor:
    replicaCount: 1
    elasticGrokFilter: tak-monitor
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
        # Nothing yet. Override to supply your own values.
        secrets:
        # Nothing yet.

  takintegration:
    elasticGrokFilter: cronjob
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.

initContainer: {} # Override to use cert-generator init container

pem_to_pfx:
  envPrefix: PEM2PFX
  pem:
    path: /opt/certs/pem
  pfx:
    path: /opt/certs/pkcs12
  trust:
    secretName: letsencrypt-r3-issuer
    pemFile: letsencrypt-r3.pem
    pfxFile: truststore.pfx
    password: password
  consumer:
    secretName: test.esb.ntjp.sjunet.org
    pemCertFile: tls.crt
    pemKeyFile: tls.key
    pfxFile: consumer.pfx
    password: password

logConfig:
  root:
    level: WARN
  loggers:
    - name: se.skltp.tak
      level: INFO
    - name: org.springframework.web
      level: WARN
    - name: org.apache.cxf
      level: WARN
    - name: org.hibernate
      level: WARN
  jsonEventTemplate:
      path: /etc/tak/tak-ecs-template.json