repository: docker.drift.inera.se/ntjp/

ingressroute:
  bksHostName: base.env.url # This should be overridden and set to your environment's base name.

container:
  takweb:
    image:
      tag: # Override to supply another image tag to run
  takservices:
    image:
      tag: # Override to supply another image tag to run
  takmonitor:
    image:
      tag: # Override to supply another image tag to run
  takintegration:
    image:
      tag: # Override to supply another image tag to run

exportCronJob:
  schedule: # Override to enable CronJob
  timeZone: "Europe/Stockholm"
  nodePattern: # Override to restrict execution to certain nodes

deployments:
  takweb:
    replicaCount: 1
    elasticGrokFilter: tak-web
    resources: #{} # The no-op curly-braces can optionally replace below sub-resources.
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 512Mi
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.
        map: 
          CATALINA_OPTS: "-XX:MaxRAMPercentage=75 -Dspring.profiles.active=production"

  takservices:
    replicaCount: 1
    elasticGrokFilter: tak-services
    resources: #{} # The no-op curly-braces can optionally replace below sub-resources.
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.
        map: 
          CATALINA_OPTS: "-XX:MaxRAMPercentage=75 -Dspring.profiles.active=production -Dlog4j2.configurationFile=/etc/tak/log4j2.xml"

  takmonitor:
    replicaCount: 1
    elasticGrokFilter: tak-monitor
    resources: #{} # The no-op curly-braces can optionally replace below sub-resources.
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 512Mi
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
        # Nothing yet. Override to supply your own values.
        secrets:
        # Nothing yet.
        map: 
          CATALINA_OPTS: "-XX:MaxRAMPercentage=75 -Dspring.profiles.active=production"

  takintegration:
    elasticGrokFilter: cronjob
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.
        map: 
          CATALINA_OPTS: "-XX:MaxRAMPercentage=75 -Dspring.profiles.active=production"


backend_resources: #{} # Comment the no-op curly-braces if you activate below commented-out resources.
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

frontend_resources: #{} # Comment the no-op curly-braces if you activate below commented-out resources.
  limits:
    memory: 512Mi
  requests:
    cpu: 75m
    memory: 512Mi

initContainer: {} # Override to use cert-generator init container

pem_to_pfx:
  envPrefix: PEM2PFX
  pem:
    path: /opt/certs/pem
  pfx:
    path: /opt/certs/pkcs12
  trust:
    secretName: letsencrypt-r3-issuer
    pemFile: letsencrypt-r3.pem
    pfxFile: truststore.pfx
    password: password
  consumer:
    secretName: test.esb.ntjp.sjunet.org
    pemCertFile: tls.crt
    pemKeyFile: tls.key
    pfxFile: consumer.pfx
    password: password

logConfig:
  root:
    level: WARN
  loggers:
    - name: se.skltp.tak
      level: INFO
    - name: org.springframework.web
      level: WARN
    - name: org.apache.cxf
      level: WARN
    - name: org.hibernate
      level: WARN
  jsonEventTemplate:
      path: /etc/tak/tak-ecs-template.json