container:
  repository: docker.drift.inera.se/ntjp/

deployments:
  takweb:
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.

  takservices:
    environment:
      variables:
        _default_config_maps:
          - tak-configmap-default
        config_maps:
          # Nothing yet. Override to supply your own values.
        secrets:
          # Nothing yet.